earth-system-radiation/pyRTE-RRTMGP

.github/workflows/conda.yml
README.md
docs/source/user_guide/installation.md

Remove macos testing to conserve CI/CD minutes

Remove macos platform

---

.github/workflows/conda.yml
CMakeLists.txt
README.md
conda.recipe/meta.yaml
docs/source/user_guide/installation.md
environment.yml
pybind_interface.cpp
pyproject.toml
tests/lw_solver_test/lw_solver_noscat_test.py
tests/test_exported_functions.py

Many small fixes in binding code

Change package name to pyrte_rrtmgp

---

docs/source/user_guide/usage.md

This is a PR to be merged into the branch for #17 
It updates the documentation to outline the future structure of our submodules.

Explain pyrte_rrtmgp submodules

---

docs/source/contributor_guide/roadmap.md
docs/source/index.rst

Add a roadmap to provide a vision for people potentially interested in contributing to the project

Expand docs

---

conda.recipe/meta.yaml
pyproject.toml

Update pyproject.toml and conda recipe to 0.0.4

Bump version to 0.0.4

---

CONTRIBUTING.md

Update contributing docs to include info about how to make a relase

Update contributing info

---

CIATATION.cff
CONTRIBUTING.md

Add citation file

---

CIATATION.cff
conda.recipe/meta.yaml
pyproject.toml

Create new release to include CITATION and trigger DOI creation at zenodo

Bump version number

---

.github/workflows/conda.yml
.gitmodules
CMakeLists.txt
README.md
build_rte_rrtmgp.sh
conda.recipe/meta.yaml
pyproject.toml
pyrte_rrtmgp/rrtmgp_data.py
tests/test_python_frontend/test_gas_optics.py
tests/test_python_frontend/test_lw_solver.py
tests/test_python_frontend/test_sw_solver.py

Make build independent of submodules

Remove submodules

---

.github/workflows/mypy.yml
README.md
pyrte_rrtmgp/tests/lw_solver_test/2stream_test/lw_solver_2stream_test.py
pyrte_rrtmgp/tests/lw_solver_test/noscat_test/lw_solver_noscat_test.py
pyrte_rrtmgp/tests/rrtmgp_compute_Planck_source_test/compute_Planck_source_test.py
pyrte_rrtmgp/tests/rrtmgp_compute_tau_absorption_test/compute_tau_absorption_test.py
pyrte_rrtmgp/tests/rrtmgp_interpolation_test/interpolation_test.py
pyrte_rrtmgp/tests/sw_solver_test/2stream_test/sw_solver_2stream_test.py
pyrte_rrtmgp/tests/test_exported_functions.py
pyrte_rrtmgp/tests/utils/data_parser.py

This is a PR for adding mypy github action

Configuring mypy github action

---

.github/workflows/mypy.yml

shortened mypy action name

---

CMakeLists.txt
conda.recipe/meta.yaml

Removed unnecessary variables and dependency on Fortran.
RTE handles the fortran dependency now

Update CMake to reduce clutter

---

pyrte_rrtmgp/data_validation.py
pyrte_rrtmgp/rte_solver.py
pyrte_rrtmgp/tests/test_data_validation.py

added data_validation helper for problem dataset with associated examples tests

---

pyrte_rrtmgp/rrtmgp_gas_optics.py
pyrte_rrtmgp/tests/test_lw_solver.py

Add additional required gases which throw ValueError if not present during gas_optics

---

conda.recipe/meta.yaml
pyrte_rrtmgp/data_validation.py
pyrte_rrtmgp/tests/test_data_validation.py

Fixed bug with data validation of dask arrays and added some additional dask-related validation tests

---

pyrte_rrtmgp/rrtmgp_gas_optics.py
pyrte_rrtmgp/rte_solver.py
pyrte_rrtmgp/tests/test_lw_solver.py

related to #178
@sehnem Hey I wrote a test on this PR which reproduces the error in the notebook so we can iterate on solving faster.

adding dask test to cover ValueError seen in lw_dask notebook

---

pyrte_rrtmgp/tests/__init__.py
pyrte_rrtmgp/tests/test_lw_solver.py
pyrte_rrtmgp/tests/test_sw_solver.py

Exception:
```python
ValueError: operands could not be broadcast together with shapes (100,18,61) (100,61)
```
@sehnem could you fix the test on this branch?
```bash
git pull
git checkout fixes-181-add-dask-test-for-swsolvernoscat
pytest pyrte_rrtmgp/tests -k test_sw_solver_noscat_dask --pdb
```

Add dask test for sw solver #181

---

.github/dependabot.yml
.github/workflows/mypy.yml

Let's keep our Github actions up to date, shall we?

Keep actions versions up to date

---

CITATION.cff
conda.recipe/meta.yaml
pyproject.toml

To be merged and a release made after #202  has been merged.

Update files for release 0.1.0

---

pyrte_rrtmgp/rrtmgp_gas_optics.py

More general and robust method for determining problem orientation in gas optics calculation (`top_at_1`). 
Addresses #219

More robust determination of orientation
